version: '3'
services:
  hadoop:
    container_name: hadoop
    hostname: hadoop 
    build:
      context: .
      dockerfile: Dockerfile
    image: hadoop:cdh6.3.0
    external_links:
    - zookeeper
    ports:
    - 9870:9870
    - 9864:9864
    - 8020:8020
    - 8042:8042
    - 8088:8088
    - 8188:8188
    - 19888:19888
    networks:
      default:
        aliases:
          - zookeeper
networks:
  default:
    external:
      name: br1