#!/bin/bash

ip=$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' hadoop)

if [ -z "$ip" ]; then
    echo -e "\nDocker container 'hadoop' not running.\n"
    exit 0;
fi

cat << -EOM
	The Hadoop Docker IP is: ${ip}

	--------------------------------------------------------------------------------
	You can now access to the following Hadoop Web GUI:

	Hadoop - NameNode:			http://$ip:50070
	Hadoop - DataNode:			http://$ip:50075
	Hadoop - YARN Node Manager:		http://$ip:8042
	Hadoop - YARN Resource Manager:		http://$ip:8088
	Hadoop - YARN Application History:	http://$ip:8188
	Hadoop - MapReduce Job History:		http://$ip:19888/jobhistory
	--------------------------------------------------------------------------------
-EOM
